services:

  redis:
    image: redis
    container_name: redis
    networks:
      - rate-limiter-project-network

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - rate-limiter-project-network

  gateway:
    ### below 3 lines when non-distributed, comment out when distributed(uses nginx)
    #container_name: gateway
    #ports:
    #  - "8080:8080"
    ###
    build: ./rate-limiter-api
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      REDIS_ADDR: ${REDIS_ADDR}
    depends_on:
      - redis
      - mysql
    networks:
      - rate-limiter-project-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gateway
    networks:
      - rate-limiter-project-network

  worker:
    build: ./analytics-worker
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      REDIS_ADDR: ${REDIS_ADDR}
    depends_on:
      - redis
      - mysql
    networks:
      - rate-limiter-project-network

networks:
  rate-limiter-project-network:
    driver: bridge

volumes:
  mysql-data:
   